services:

  test:
    build: .
    container_name: playwright-test
    depends_on:
      - redis
      - mysql


  mysql:
    image: mysql:8.0
    container_name: test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"


  redis:
    image: redis:7
    container_name: test-redis
    ports:
      - "6379:6379"