name: Deploy Playwright Service


on:

  push:
    branches:
      - main


jobs:

  deploy:

    runs-on:
      - self-hosted
      - Windows


    steps:


    - name: Checkout code
      uses: actions/checkout@v4



    - name: Check files
      shell: powershell
      run: |

        pwd
        dir



    - name: Build Docker image
      shell: powershell
      run: |

        docker build -t playwright-test:latest .



    - name: Remove old container
      shell: powershell
      run: |

        docker rm -f playwright-service 2>$null || echo "No old container"



    - name: Start container
      shell: powershell
      run: |

        docker run -d `
          --name playwright-service `
          --restart always `
          playwright-test:latest



    - name: Verify container
      shell: powershell
      run: |

        docker ps