name: Playwright Test


on:

  push:

  pull_request:


jobs:

  test:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout code
      uses: actions/checkout@v6


    - name: Build Docker image
      run:

        docker build -t playwright-test .


    - name: Run Test
      run:

        docker run playwright-test
